# Generated by Django 5.0.6 on 2024-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klub_100kilo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservations",
            name="date",
        ),
        migrations.AddField(
            model_name="reservations",
            name="end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservations",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="reservations",
            name="start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
