# Generated by Django 5.0.6 on 2024-06-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klub_100kilo", "0002_traningsexercises_alter_trainings_exercises_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainings",
            name="trainer_id",
        ),
        migrations.AlterField(
            model_name="trainings",
            name="took_place",
            field=models.BooleanField(default=False),
        ),
    ]
