# Generated by Django 5.0.6 on 2024-06-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klub_100kilo", "0003_alter_reservations_gym_alter_reservations_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurementsgoals",
            name="name",
            field=models.CharField(default="Brak nazwy", max_length=100),
            preserve_default=False,
        ),
    ]
