# Generated by Django 5.0.6 on 2024-06-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klub_100kilo", "0004_measurementsgoals_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservations",
            name="training_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
